#!/usr/bin/python3
import sys
import math
def pollards_rho(n):
    if n % 2 == 0:
        return 2

    x = 2
    y = 2
    d = 1

    f = lambda x: (x**2 + 1) % n

    while d == 1:
        x = f(x)
        y = f(f(y))
        d = math.gcd(abs(x - y), n)

    return d
with open(sys.argv[1], 'r') as file:
    for line in file:
        n = int(line)
        i = pollards_rho(n)
        print(f'{n}={n//i}*{i}')
