#!/usr/bin/python3
import sys
import math
def pollards_rho(n):
    if n % 2 == 0:
        return 2

    x = 2
    y = 2
    d = 1

    f = lambda x: (x**2 + 1) % n

    while d == 1:
        x = f(x)
        y = f(f(y))
        d = math.gcd(abs(x - y), n)

    return d
def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(math.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True
with open(sys.argv[1], 'r') as file:
    for line in file:
        n = int(line)
        x = n
        while True:
            i = pollards_rho(x)
            if is_prime(n//i):
                print(f'{n}={i}*{n//i}')
                break
            x //= i
